from __future__ import annotations

import argparse
import ast
import importlib
import re
import sys
from collections.abc import Callable, Sequence
from pathlib import Path
from pprint import pformat
from types import ModuleType
from typing import Any, cast

from pathbridge import version
from pathbridge.compiler import compile_rules
from pathbridge.extras.shaper import make_shape
from pathbridge.extras.trace import build_rules
from pathbridge.types import CompiledRulesT

_GENERATED_MODULE_DOC = '"""Generated by pathbridge compile. Do not edit manually."""'


class CliError(Exception):
    """Raised when CLI arguments are invalid at runtime."""


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="pathbridge",
        description="PathBridge command line tools.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {version}",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    compile_parser = subparsers.add_parser(
        "compile",
        help="Generate a Python module with compiled mapping rules.",
        description=(
            "Build shape -> trace rules -> compile rules and write an importable "
            "Python module with RAW_RULES and COMPILED_RULES constants."
        ),
    )
    compile_parser.set_defaults(handler=_handle_compile)

    required = compile_parser.add_argument_group("required arguments")
    required.add_argument(
        "--output-package",
        required=True,
        help="Filesystem path to output Python package directory.",
    )
    required.add_argument(
        "--facade-class",
        required=True,
        help="Import path to facade dataclass type (module:ClassName).",
    )
    required.add_argument(
        "--model-module",
        required=True,
        help="Import path to destination model module (e.g. pkg.models).",
    )
    required.add_argument(
        "--converter",
        required=True,
        help="Import path to converter callable (module:function).",
    )

    output_options = compile_parser.add_argument_group("output options")
    output_options.add_argument(
        "--output-module",
        default="compiled_rules",
        help="Output module file name without .py suffix (default: compiled_rules).",
    )

    shape_options = compile_parser.add_argument_group("make_shape options")
    shape_options.add_argument(
        "--shape-list-len",
        type=int,
        default=1,
        help="Default list length for generated shape (default: 1).",
    )
    shape_options.add_argument(
        "--shape-override",
        action="append",
        default=[],
        metavar="PATH=VALUE",
        help=(
            "Override for make_shape, may be repeated. VALUE is parsed with "
            "ast.literal_eval and falls back to raw string."
        ),
    )

    rules_options = compile_parser.add_argument_group("build_rules options")
    rules_options.add_argument(
        "--rules-root-tag",
        default="root",
        help="Facade root segment used when tracing rules (default: root).",
    )
    rules_options.add_argument(
        "--rules-lift",
        action="append",
        default=[],
        metavar="NAME",
        help=(
            "Function name (or module:function) to lift while tracing. Can be repeated."
        ),
    )

    return parser


def _parse_override(item: str) -> tuple[str, Any]:
    if "=" not in item:
        raise CliError(
            f"Invalid --shape-override value {item!r}. Expected format PATH=VALUE."
        )
    path, raw_value = item.split("=", 1)
    if not path:
        raise CliError(
            f"Invalid --shape-override value {item!r}. PATH segment is empty."
        )
    try:
        value = ast.literal_eval(raw_value)
    except (ValueError, SyntaxError):
        value = raw_value
    return path, value


def _parse_overrides(values: Sequence[str]) -> dict[str, Any]:
    overrides: dict[str, Any] = {}
    for value in values:
        path, parsed = _parse_override(value)
        overrides[path] = parsed
    return overrides


def _load_module(module_path: str) -> ModuleType:
    try:
        return importlib.import_module(module_path)
    except ModuleNotFoundError as exc:
        raise CliError(f"Cannot import module {module_path!r}.") from exc


def _load_object(import_path: str) -> Any:
    if ":" not in import_path:
        raise CliError(
            f"Invalid import path {import_path!r}. Expected format module:object."
        )
    module_path, attr_name = import_path.split(":", 1)
    if not module_path or not attr_name:
        raise CliError(
            f"Invalid import path {import_path!r}. Expected format module:object."
        )

    module = _load_module(module_path)
    obj: Any = module
    for part in attr_name.split("."):
        if not hasattr(obj, part):
            raise CliError(f"Object {attr_name!r} not found in module {module_path!r}.")
        obj = getattr(obj, part)
    return obj


def _format_regex_flags(flags: int) -> str:
    known = [
        ("ASCII", re.ASCII),
        ("IGNORECASE", re.IGNORECASE),
        ("LOCALE", re.LOCALE),
        ("MULTILINE", re.MULTILINE),
        ("DOTALL", re.DOTALL),
        ("UNICODE", re.UNICODE),
        ("VERBOSE", re.VERBOSE),
    ]
    remaining = flags
    parts: list[str] = []
    for name, flag in known:
        if remaining & flag:
            parts.append(f"re.{name}")
            remaining &= ~flag
    if remaining:
        parts.append(str(remaining))
    if not parts:
        return "0"
    return " | ".join(parts)


def _build_module_source(
    *,
    raw_rules: dict[str, str],
    compiled_rules: CompiledRulesT,
) -> str:
    sorted_rules = dict(sorted(raw_rules.items()))
    raw_literal = pformat(sorted_rules, width=88, sort_dicts=False)

    compiled_lines = ["["]
    for pattern, template in compiled_rules:
        flags_expr = _format_regex_flags(pattern.flags)
        compiled_lines.append(
            f"    (re.compile({pattern.pattern!r}, {flags_expr}), {template!r}),"
        )
    compiled_lines.append("]")
    compiled_literal = "\n".join(compiled_lines)

    return "\n".join(
        [
            _GENERATED_MODULE_DOC,
            "from __future__ import annotations",
            "",
            "import re",
            "",
            "from pathbridge.types import CompiledRulesT, RawRulesMapT",
            "",
            f"RAW_RULES: RawRulesMapT = {raw_literal}",
            "",
            f"COMPILED_RULES: CompiledRulesT = {compiled_literal}",
            "",
            '__all__ = ["RAW_RULES", "COMPILED_RULES"]',
            "",
        ]
    )


def _write_generated_package(
    *,
    package_dir: Path,
    module_name: str,
    module_source: str,
) -> Path:
    package_dir.mkdir(parents=True, exist_ok=True)

    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("", encoding="utf-8")

    module_path = package_dir / f"{module_name}.py"
    module_path.write_text(module_source, encoding="utf-8")
    return module_path


def _handle_compile(args: argparse.Namespace) -> int:
    if args.shape_list_len < 1:
        raise CliError("--shape-list-len must be >= 1.")
    if not args.output_module.isidentifier():
        raise CliError(
            f"--output-module must be a valid Python identifier, got {args.output_module!r}."
        )

    facade_class = _load_object(args.facade_class)
    converter = _load_object(args.converter)
    model_module = _load_module(args.model_module)
    overrides = _parse_overrides(args.shape_override)
    rules_lift: Sequence[str] | None = args.rules_lift if args.rules_lift else None

    shape = make_shape(
        facade_class,
        list_len=args.shape_list_len,
        overrides=overrides or None,
    )
    raw_rules = build_rules(
        model_module=model_module,
        converter=converter,
        shape=shape,
        lift=rules_lift,
        root_tag=args.rules_root_tag,
    )
    compiled_rules = compile_rules(raw_rules)

    module_source = _build_module_source(
        raw_rules=raw_rules,
        compiled_rules=compiled_rules,
    )
    output_path = _write_generated_package(
        package_dir=Path(args.output_package),
        module_name=args.output_module,
        module_source=module_source,
    )

    print(f"Generated: {output_path}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    handler = cast(Callable[[argparse.Namespace], int], args.handler)
    try:
        return handler(args)
    except CliError as exc:
        parser.error(str(exc))
    except Exception as exc:  # pragma: no cover - defensive
        print(f"pathbridge: error: {exc}", file=sys.stderr)
        return 1
    return 1
