from __future__ import annotations

import argparse
import ast
import hashlib
import importlib
import importlib.util
import re
import sys
from collections.abc import Callable, Sequence
from pathlib import Path
from pprint import pformat
from types import ModuleType
from typing import Any, cast

from pathbridge import version
from pathbridge.compiler import compile_rules
from pathbridge.extras.shaper import make_shape
from pathbridge.extras.trace import build_rules
from pathbridge.types import CompiledRulesT

_GENERATED_MODULE_DOC = '"""Generated by pathbridge compile. Do not edit manually."""'
_LOADED_FILE_MODULES: dict[Path, ModuleType] = {}


class CliError(Exception):
    """Raised when CLI arguments are invalid at runtime."""


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="pathbridge",
        description="PathBridge command line tools.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {version}",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    compile_parser = subparsers.add_parser(
        "compile",
        help="Generate a Python module with compiled mapping rules.",
        description=(
            "Build shape -> trace rules -> compile rules and write an importable "
            "Python module with RAW_RULES and COMPILED_RULES constants."
        ),
    )
    compile_parser.set_defaults(handler=_handle_compile)

    required = compile_parser.add_argument_group("required arguments")
    required.add_argument(
        "--output-package",
        required=True,
        help="Dotted Python package name for generated output (e.g. pkg.rules).",
    )
    required.add_argument(
        "--output-dir",
        default=".",
        help=(
            "Base directory where output package tree is created "
            "(default: current directory)."
        ),
    )
    required.add_argument(
        "--facade-class",
        required=True,
        help=(
            "Facade dataclass reference: module:ClassName or path/to/file.py:ClassName."
        ),
    )
    required.add_argument(
        "--destination-module",
        required=True,
        help=("Destination module reference: module.path or path/to/file.py."),
    )
    required.add_argument(
        "--facade-to-destination",
        required=True,
        help=(
            "Facade->destination callable reference: module:function or "
            "path/to/file.py:function."
        ),
    )

    output_options = compile_parser.add_argument_group("output options")
    output_options.add_argument(
        "--output-module",
        default="compiled_rules",
        help="Output module file name without .py suffix (default: compiled_rules).",
    )
    output_options.add_argument(
        "--emit",
        choices=("both", "raw", "compiled"),
        default="both",
        help=(
            "Choose what constants to emit into generated module: "
            "both, raw, or compiled (default: both)."
        ),
    )

    shape_options = compile_parser.add_argument_group("make_shape options")
    shape_options.add_argument(
        "--shape-list-len",
        type=int,
        default=1,
        help="Default list length for generated shape (default: 1).",
    )
    shape_options.add_argument(
        "--shape-override",
        action="append",
        default=[],
        metavar="PATH=VALUE",
        help=(
            "Override for make_shape, may be repeated. VALUE is parsed with "
            "ast.literal_eval and falls back to raw string."
        ),
    )

    rules_options = compile_parser.add_argument_group("build_rules options")
    rules_options.add_argument(
        "--facade-root-tag",
        default="root",
        help="Facade root segment used when tracing rules (default: root).",
    )
    rules_options.add_argument(
        "--lift-functions",
        action="append",
        default=[],
        metavar="NAME",
        help=(
            "Function name (or module:function) to lift while tracing. Can be repeated."
        ),
    )

    return parser


def _parse_override(item: str) -> tuple[str, Any]:
    if "=" not in item:
        raise CliError(
            f"Invalid --shape-override value {item!r}. Expected format PATH=VALUE."
        )
    path, raw_value = item.split("=", 1)
    if not path:
        raise CliError(
            f"Invalid --shape-override value {item!r}. PATH segment is empty."
        )
    try:
        value = ast.literal_eval(raw_value)
    except (ValueError, SyntaxError):
        value = raw_value
    return path, value


def _parse_overrides(values: Sequence[str]) -> dict[str, Any]:
    overrides: dict[str, Any] = {}
    for value in values:
        path, parsed = _parse_override(value)
        overrides[path] = parsed
    return overrides


def _load_module(module_path: str) -> ModuleType:
    if module_path.endswith(".py"):
        return _load_file_module(module_path)
    try:
        return importlib.import_module(module_path)
    except ModuleNotFoundError as exc:
        raise CliError(f"Cannot import module {module_path!r}.") from exc


def _load_file_module(file_path: str) -> ModuleType:
    path = Path(file_path).expanduser().resolve()
    if path.suffix != ".py":
        raise CliError(f"Expected a Python file ending with .py, got {file_path!r}.")
    if not path.is_file():
        raise CliError(f"Python file {str(path)!r} does not exist.")

    cached = _LOADED_FILE_MODULES.get(path)
    if cached is not None:
        return cached

    module_name, package_root = _infer_module_name(path)
    if module_name is not None:
        if package_root is not None:
            package_root_str = str(package_root)
            if package_root_str not in sys.path:
                sys.path.insert(0, package_root_str)
        module = importlib.import_module(module_name)
        _LOADED_FILE_MODULES[path] = module
        return module

    synthetic_name = f"pathbridge_user_{hashlib.sha1(str(path).encode()).hexdigest()}"
    spec = importlib.util.spec_from_file_location(synthetic_name, path)
    if spec is None or spec.loader is None:
        raise CliError(f"Cannot load module from file {str(path)!r}.")

    module = importlib.util.module_from_spec(spec)
    sys.modules[synthetic_name] = module
    spec.loader.exec_module(module)
    _LOADED_FILE_MODULES[path] = module
    return module


def _infer_module_name(path: Path) -> tuple[str | None, Path | None]:
    """
    Infer dotted module name from a package file path.

    Example:
      /repo/tests/integration/foo.py -> ("tests.integration.foo", /repo)
    when all intermediate package dirs contain __init__.py.
    """
    package_parts = [path.stem]
    parent = path.parent

    while (parent / "__init__.py").is_file():
        package_parts.append(parent.name)
        parent = parent.parent

    if len(package_parts) == 1:
        return None, None

    package_parts.reverse()
    return ".".join(package_parts), parent


def _load_object(import_path: str) -> Any:
    if ":" not in import_path:
        raise CliError(
            f"Invalid import path {import_path!r}. Expected format module_or_file:object."
        )
    module_path, attr_name = import_path.split(":", 1)
    if not module_path or not attr_name:
        raise CliError(
            f"Invalid import path {import_path!r}. Expected format module_or_file:object."
        )

    module = _load_module(module_path)
    obj: Any = module
    for part in attr_name.split("."):
        if not hasattr(obj, part):
            raise CliError(f"Object {attr_name!r} not found in module {module_path!r}.")
        obj = getattr(obj, part)
    return obj


def _parse_package_name(name: str) -> list[str]:
    parts = [part for part in name.split(".") if part]
    if not parts:
        raise CliError(
            f"--output-package must be a dotted Python package name, got {name!r}."
        )
    for part in parts:
        if not part.isidentifier():
            raise CliError(
                f"--output-package has invalid segment {part!r}; "
                "all segments must be valid Python identifiers."
            )
    return parts


def _format_regex_flags(flags: int) -> str:
    known = [
        ("ASCII", re.ASCII),
        ("IGNORECASE", re.IGNORECASE),
        ("LOCALE", re.LOCALE),
        ("MULTILINE", re.MULTILINE),
        ("DOTALL", re.DOTALL),
        ("UNICODE", re.UNICODE),
        ("VERBOSE", re.VERBOSE),
    ]
    remaining = flags
    parts: list[str] = []
    for name, flag in known:
        if remaining & flag:
            parts.append(f"re.{name}")
            remaining &= ~flag
    if remaining:
        parts.append(str(remaining))
    if not parts:
        return "0"
    return " | ".join(parts)


def _build_module_source(
    *,
    raw_rules: dict[str, str] | None,
    compiled_rules: CompiledRulesT | None,
) -> str:
    exports: list[str] = []
    body: list[str] = []

    if raw_rules is not None:
        sorted_rules = dict(sorted(raw_rules.items()))
        raw_literal = pformat(sorted_rules, width=88, sort_dicts=False)
        body.append(f"RAW_RULES: RawRulesMapT = {raw_literal}")
        body.append("")
        exports.append("RAW_RULES")

    if compiled_rules is not None:
        compiled_lines = ["["]
        for pattern, template in compiled_rules:
            flags_expr = _format_regex_flags(pattern.flags)
            compiled_lines.append(
                f"    (re.compile({pattern.pattern!r}, {flags_expr}), {template!r}),"
            )
        compiled_lines.append("]")
        compiled_literal = "\n".join(compiled_lines)
        body.append(f"COMPILED_RULES: CompiledRulesT = {compiled_literal}")
        body.append("")
        exports.append("COMPILED_RULES")

    return "\n".join(
        [
            _GENERATED_MODULE_DOC,
            "from __future__ import annotations",
            "",
            "import re",
            "",
            "from pathbridge.types import CompiledRulesT, RawRulesMapT",
            "",
            *body,
            f"__all__ = {exports!r}",
            "",
        ]
    )


def _write_generated_package(
    *,
    output_dir: Path,
    package_name: str,
    module_name: str,
    module_source: str,
) -> Path:
    if output_dir.exists() and not output_dir.is_dir():
        raise CliError(f"--output-dir {str(output_dir)!r} is not a directory.")
    output_dir.mkdir(parents=True, exist_ok=True)

    package_dir = output_dir
    for segment in _parse_package_name(package_name):
        package_dir = package_dir / segment
        package_dir.mkdir(parents=True, exist_ok=True)
        init_path = package_dir / "__init__.py"
        if not init_path.exists():
            init_path.write_text("", encoding="utf-8")

    module_path = package_dir / f"{module_name}.py"
    module_path.write_text(module_source, encoding="utf-8")
    return module_path


def _handle_compile(args: argparse.Namespace) -> int:
    if args.shape_list_len < 1:
        raise CliError("--shape-list-len must be >= 1.")
    if not args.output_module.isidentifier():
        raise CliError(
            f"--output-module must be a valid Python identifier, got {args.output_module!r}."
        )
    _parse_package_name(args.output_package)

    facade_class = _load_object(args.facade_class)
    facade_to_destination = _load_object(args.facade_to_destination)
    destination_module = _load_module(args.destination_module)
    overrides = _parse_overrides(args.shape_override)
    lift_functions: Sequence[str] | None = (
        args.lift_functions if args.lift_functions else None
    )

    shape = make_shape(
        facade_class,
        list_len=args.shape_list_len,
        overrides=overrides or None,
    )
    raw_rules = build_rules(
        destination_module=destination_module,
        facade_to_destination=facade_to_destination,
        facade_shape=shape,
        lift_functions=lift_functions,
        facade_root_tag=args.facade_root_tag,
    )
    compiled_rules: CompiledRulesT | None = None
    if args.emit in ("both", "compiled"):
        compiled_rules = compile_rules(raw_rules)

    module_source = _build_module_source(
        raw_rules=raw_rules if args.emit in ("both", "raw") else None,
        compiled_rules=compiled_rules,
    )
    output_path = _write_generated_package(
        output_dir=Path(args.output_dir),
        package_name=args.output_package,
        module_name=args.output_module,
        module_source=module_source,
    )

    print(f"Generated: {output_path}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    handler = cast(Callable[[argparse.Namespace], int], args.handler)
    try:
        return handler(args)
    except CliError as exc:
        parser.error(str(exc))
    except Exception as exc:  # pragma: no cover - defensive
        print(f"pathbridge: error: {exc}", file=sys.stderr)
        return 1
    return 1
