name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    env:
      UV_EXTRA_ARGS: --with "${{ matrix.marshmallow }}"

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python ${{ matrix.python-version }}
        run: echo ${{ matrix.python-version }} > .python-version

      - name: Install dependencies
        run: make deps

      - name: Lint
        run: make lint

      - name: Type check
        run: make typecheck

      - name: Build docs
        if: matrix.python-version == '3.12'
        run: make docs-build

      - name: Test
        run: make test

  build:
    name: Build & Publish Package
    runs-on: ubuntu-latest
    needs: test
    # Run only on pushing a version tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    environment: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build package
        run: make build

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
